### ISSUE TITLE
Mutual TLS Support

### ISSUE THREAD

**Issue by ghost** [yfinkelstein/node-zookeeper#136]
Does this have the same support for Client cert authentication as outlined here: [https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZooKeeper+SSL+User+Guide](url)

**Comment by kuebk** [comment]
No, it doesn't have support for this feature.

**Comment by DavidVujic** [comment]
> feat: Use ZooKeper client v3.6.3 #289

Hi @mobini0, sorry for the late reply. I'm not that familiar with mTLS in general, but it could/should be possible to do the same as with the C Client (since this project is a Node.js wrapper around it). Would you be able to help out with researching what is possible with the official C ZooKeeper client, and create an issue here?
