### ISSUE TITLE
Incorrect use of SemVer

### ISSUE THREAD

**Issue by Gisleburt** [yfinkelstein/node-zookeeper#137]
In Semantic Versioning, `x.y.z-anything` is a lower version than `x.y.z`. The fact that the latest release (at time of writing) is `3.4.9-3` and there also seems to be a `3.4.9` is confusing `npm outdated`:

```
➜  git:(remove-redundant-port-variable) ✗  npm outdated
Package    Current  Wanted   Latest  Location
zookeeper  3.4.9-3   3.4.9  3.4.9-3  zookeeper-updater

➜  git:(remove-redundant-port-variable) ✗  npm update zookeeper

...
...
...

➜  git:(remove-redundant-port-variable) ✗  npm outdated        
Package    Current  Wanted   Latest  Location
zookeeper    3.4.9   3.4.9  3.4.9-3  zookeeper-updater
```

My package.json contains:
```"zookeeper": "^3.4.9-3"```

The weird thing is I don't see a 3.4.9 release anywhere :/

**Comment by kuebk** [comment]
node-zookeeper versioning is connected to zookeper versioning.
Let's take 3.4.9-3 as an example, 3.4.9 is zookeper version which was used, -3 is the version of node-zookeeper based on given zookeeper version.

Last time we talked about this we've decided we are not going to change this, but maybe other contributors have changed their minds in meantime.

**Comment by DavidVujic** [comment]
In a fork with ongoing work for adding Windows support, I have used semver. That is because of breaking features in the fork (dropping support for really old nodejs versions).

Semver will help users of this package to not break any automated builds. Example: a `dependencies` section with wildcard for this package (`zookeeper: "3.4.x"`)

See this issue for more info (and a cry for C/C++ help!):
https://github.com/yfinkelstein/node-zookeeper/issues/78#issuecomment-453748000
