### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by DavidVujic** [yfinkelstein/node-zookeeper#162]
Add a pull request template. https://github.com/yfinkelstein/node-zookeeper/community

**Comment by DavidVujic** [comment]
Solved in https://github.com/yfinkelstein/node-zookeeper/pull/167

**Comment by jbienkowski311** [comment]
There is a great repository with many examples of GH issue templates: https://github.com/stevemao/github-issue-templates. I personally like `questions-answers` a lot, I would remove the Screenshots section, otherwise it is ready to go. Please let me know if you would like me to create a PR with this particular one or some other template.

**Comment by DavidVujic** [comment]
@jbienkowski311 Looks good, thanks! Yes, I would like a PR for the particular template. If you think this project should have more templates, you are welcome to create more pull requests!
