### ISSUE TITLE
Library is Vulnerable Due To Unneeded Dependency

### ISSUE THREAD

**Issue by mwaeckerlin** [yfinkelstein/node-zookeeper#277]
**Describe the bug**

Please move dependency on:
```
        "decompress": "4.2.x",
        "decompress-targz": "4.1.x",
``` 
from:
```
    "dependencies": {
```
to:
```
    "devDependencies": {
```

Reasons:

1. They are only used in `prepublish.js`
2. Any product that includes `zookeeper` is vulnerable due to dependency on `decompress`.

**To Reproduce**
1. Create a Docker Image with zookeeper dependency 
2. Run X-Ray scanner

**Expected behavior**
1. Dependencies only used in build environment should be in devDependecies
2. zookeeper should not depend on vulnerable packages

**Screenshots**
Found by X-Ray in JFrog.

<img width="897" alt="grafik" src="https://user-images.githubusercontent.com/4056726/119692690-e7759700-be4b-11eb-8685-c7453a4c56af.png">

**Desktop (please complete the following information):**
 - OS: Linux
 - Node.js version: v14.16.1
 - C/C++ compiler and version:  n/a

**Comment by DavidVujic** [comment]
Thank you @mwaeckerlin! The `npm audit` tool hasn't notified about this dependency earlier. 

In cases where the included pre-builds does not match the current OS, the installer will build a Node.js AddOn, and will use the decompress tool.

However, the footprint for the C based source code (included in this repo) maybe could be added directly and not zipped. 

I will investigate this further.

Thank you for reporting!

**Comment by mwaeckerlin** [comment]
Hi @DavidVujic, thank you for the quick response. Yes, the docker image scanner found some more vulnerabilities than our local `npm audit`.

In a first step, it would already help to just move those from `dependencies` to `devDependencies`. That should not affect any functionality.

You can then implement a clean solution later.

For our project, it would be very helpful, if we could get a patch soon.

**Comment by DavidVujic** [comment]
@mwaeckerlin Can you provide some details from the tool about the security issue? `decompress` has about 4 million downloads a week according to npm, and I am surprised about not getting any audit issues for it or by googling.

Currently, it is not possible to move the dependency to `devDependencies` because it will break all installs on Linux systems (that doesn't use the prebuilds of this library).

**Comment by mwaeckerlin** [comment]
@DavidVujic, I can get this additional information, when open the report:
> All versions of `decompress` are vulnerable to arbitrary file write. the package fails to prevent extraction of files with relative paths, allowing attackers to write to any folder in the system by including filenames containing`../`.

<img width="637" alt="grafik" src="https://user-images.githubusercontent.com/4056726/119897590-f25e2380-bf40-11eb-82a6-0618cba81824.png">

I hope, that helps.

**Comment by DavidVujic** [comment]
> The library is not needed in production, so it should go to `devDependencies`. Even though the vulnerability is most probably not relevant in your setup, it's better not to have the package in a production release. Unneeded dependencies also blow up the docker image.

Thank you!

I'm pretty sure `decrompress` is needed in production, though. Because when you run `npm install` - this library will build a native Node.js addon that is fit for the current machine, from the official Apache Zookeeper source code.

The Apache source code is stored in a `zip` file in the `deps` folder of this package. Unzipping is made with the `decompress` package.

Only when you run `npm install` from a OSX or Windows machine, this step is bypassed because there are already prebuilt binaries for those operating systems.

**Comment by DavidVujic** [comment]
@mwaeckerlin Are you sure this is valid for `v4.2.1` of `decompress`?

The date of the report you attached as as screenshot looks like it is from 2019, or am I misinterpreting it?

Here are some details: https://snyk.io/vuln/SNYK-JS-DECOMPRESS-557358

**Comment by mwaeckerlin** [comment]
@DavidVujic, so decompress is required at installation, not at runtime.

The problem with `dependencies` vs `devDependencies`: In NodeJS, there is nothing like «Webpack» that would filter only the required files for the final deployment. So to deploy, you need to copy the built `dist` (or `build`) directory plus `node_modules`, which also contains a lot of unneeded crap. The only optimization that can be done, as far as I know, is to build `node_modules` with flag `NODE_ENV='develop'` to avoid at least the build-time packages from being published. That's why I ask to put the library to `devDependencies`.

Probably the vulnerability is from 2019 and not fixed yet. The image is from May 20, 2021:
<img width="163" alt="grafik" src="https://user-images.githubusercontent.com/4056726/119948096-c9697d00-bf98-11eb-888e-ebf57e358f5b.png">


----

For your understanding, this is our `Dockerfile`:
```
FROM sygnum/nodejs-build:v1.0.0 as prod-modules
COPY --chown=${RUN_USER} package.json yarn.lock .yarnrc.yml ./
COPY --chown=${RUN_USER} .yarn/ ./.yarn/
RUN sh -c "${DO_YARN_INSTALL_PROD}"

FROM prod-modules as build-modules
RUN sh -c "${DO_YARN_INSTALL_DEV}"

FROM sygnum/nodejs-dev:v1.0.0 as development
COPY --from=build-modules /srv/node_modules /srv/node_modules
COPY --chown=${RUN_USER} . .
WORKDIR /srv
EXPOSE 3000

FROM build-modules as build
COPY --chown=${RUN_USER} . .
RUN sh -c "${DO_YARN_BUILD}"

FROM sygnum/nodejs:v1.0.1 as production
COPY --from=prod-modules /srv/node_modules /srv/node_modules
COPY --from=build /srv/dist /srv/
COPY --from=build /srv/static /srv/static
COPY --from=build /srv/fonts /srv/fonts
EXPOSE 3000
```

Where `DO_YARN_INSTALL_PROD` is the yarn2-version of `NODE_ENV='production` npm install`, and `DO_YARN_INSTALL_DEV`the yarn2-version of `NODE_ENV='develop` npm install`:
```
DO_YARN_INSTALL_DEV="yarn plugin import workspace-tools && yarn workspaces focus --all"
DO_YARN_INSTALL_PROD="yarn plugin import workspace-tools && yarn workspaces focus --production"
```

**Comment by DavidVujic** [comment]
@mwaeckerlin Thanks!

As I understand npm, it will run `npm install` for each dependency that is added in package.json.

So if you have added `zookeeper` to your package.json file and type `npm install` in your app, it will run install for your dependencies too. I don't think npm packages includes their own `node_modules` folder. With that said, I think the `prepublish.js` file will run when you install your app.

For the original issue: can you please verify the accuracy of the report? The link I shared in the previous post tells about the issue was solved in the version of `decompress` that we use here in the zookeeper package.

**Comment by mwaeckerlin** [comment]
> I think the `prepublish.js` file will run when you install your app.

@DavidVujic, what exactly does this mean, in what step will it run?
- `npm install`
- `npm build`
if it runs in `npm build`, then it should be fine in `devDependencies`, you don't need it in production.

Regarding the link, sorry, missed that. Unfortunately, I have no access to our repository and its configuration, since it's hosted on a 3rd party. But in fact, it looks like the message was outdated. I'll report that to our SRE team.

Decompress resolves to `4.2.1`, which should be fine according to the information in your link.

**Comment by DavidVujic** [comment]
When you install your app, this is what will happen in zookeeper:

(from the package.json file of this library)
```json
"install": "node ./scripts/prepublish.js && npm run build",
```

**Comment by mwaeckerlin** [comment]
I never call `install`, so it seems to be non needed.

**Comment by DavidVujic** [comment]
> I never call `install`, so it seems to be non needed.

Now I am confused :smile: 

To install a dependency, you would have to run `npm install` somewhere, right?

**Comment by mwaeckerlin** [comment]
Sorry, my bad. But is that `npm install` or `npm run install`? Normally `npm install` does not include `buld`, so I'm confused. I'll have to check, what really happens...

**Comment by DavidVujic** [comment]
> Sorry, my bad. But is that `npm install` or `npm run install`? Normally `npm install` does not include `buld`, so I'm confused. I'll have to check, what really happens...

No worries!

The zookeeper `build` command is just an internally used script, and it is triggered by the "official" `install` script used by the ones that has added it as a dependency.

So, when you install the dependencies of your app, each one of them will run `install` behind the scenes.

**Comment by mwaeckerlin** [comment]
I see, it runs, when I call `npm i zookeeper` → but that means, it's not needed at runtime.

**Comment by DavidVujic** [comment]
> I see, it runs, when I call `npm i zookeeper` → but that means, it's not needed at runtime of the final product.

Ah, I see your point!

`devDependencies` are used when developing locally. If you would contribute to zookeeper, you would need to have unit testing tools and things like that installed. And those will be pulled from npm when added in the `devDependencies` section.

To be able to use a package from npm, all required dependencies that the library need to be able to run in production has to live in the `dependencies` part of package.json.

That is why `decompress` is not a dev-dependency, beacuse without it nothing will work.

When you run `npm install` in **your** app, the dependencies will also run their own `install` and their dependencies in turn will do the same. In this scenario,  `devDependencies` is not used. Because it is a production enabled install. 

Hope this clear things up!

**Comment by DavidVujic** [comment]
I'm closing this issue, since the original question about vulnerability is :heavy_check_mark: 

Please reopen if you think it need any actions.

**Comment by wareczek** [comment]
@DavidVujic could you reopen that? Vulnerability is still valid: https://github.com/advisories/GHSA-mp2f-45pm-3cg9
Recommendation is to switch to @xhmikosr/decompress package.

**Comment by DavidVujic** [comment]
I'll have a look!

**Comment by DavidVujic** [comment]
Continuing in #361 

(closing this again, since the original issue and title is not applicable)
